Prevent natural spawning oxygen needed entities at deoxygenated level
terrarium-earth/Ad-Astra pull request #357
Opened 2023-08-17 11:16 UTC by gisellevonbingen

Oxygen needed entities will be spawn in oxygen provided area.
e.g.) Alex's Mobs's fly
![image](https://github.com/terrarium-earth/Ad-Astra/assets/44163945/5fd938cd-8cfa-4cd4-a8ec-921696f69c63)

2023-08-17 12:01 UTC, ThatGravyBoat requested changes

2023-08-17 12:01 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/ad_astra/mixin/MobMixin.java
> +            Mob mob = (Mob) (Object) this;
Change the class to extend living entity and then pass `this` into the method instead of needing to self cast

2023-08-17 12:01 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/ad_astra/common/entity/system/EntityOxygenSystem.java
> +    public enum EntityOxygenStatus {
For better visibility please make this its own class

2023-08-17 12:07 UTC, gisellevonbingen commented on common/src/main/java/earth/terrarium/ad_astra/mixin/MobMixin.java
> +            Mob mob = (Mob) (Object) this;
Did you mean change to 'LivingEntity entity = ((LivingEntity) (Object) this)' ?

2023-08-17 12:08 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/ad_astra/mixin/MobMixin.java
> +            Mob mob = (Mob) (Object) this;
```java
public abstract class MobMixin extends LivingEntity {
...
if (EntityOxygenSystem.getOxygenStatus(this, level) == EntityOxygenStatus.DAMAGE) {
```

2023-08-17 12:08 UTC, ThatGravyBoat commented on common/src/main/java/earth/terrarium/ad_astra/mixin/MobMixin.java
> +            Mob mob = (Mob) (Object) this;
thats what I meant

2023-08-17 12:24 UTC, gisellevonbingen commented on common/src/main/java/earth/terrarium/ad_astra/mixin/MobMixin.java
> +            Mob mob = (Mob) (Object) this;
OK all done.

2023-08-18 20:27 UTC, ThatGravyBoat approved these changes

2023-10-31 16:22 UTC, AlexNijjar approved these changes

2023-10-31 16:22 UTC, merged