fix: remove REI compat layer for CompressingDisplay
terrarium-earth/Ad-Astra pull request #521
Opened 2024-03-23 22:02 UTC by KiriKaz

# What was done
---
Removed REI compatibility layer from affecting CompactingDisplay, as that was causing crashes.
Refer to https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/23#issuecomment-1332489186

I do not have experience with Minecraft modding, so unsure if this is the correct way to go about it
If incorrect, please do check. Have been waiting for this fix for a couple of weeks now.

Issue #499.

# Why is this change needed
---
Crashes are bad.

2024-03-23 22:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/terrarium-earth/Ad-Astra?pullRequest=521) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/terrarium-earth/Ad-Astra?pullRequest=521) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/terrarium-earth/Ad-Astra?pullRequest=521) it.</sub>

2024-03-23 22:03 UTC, KiriKaz commented
Love to get a review on this if possible

2024-03-24 01:24 UTC, AlexNijjar requested changes

2024-03-24 01:24 UTC, AlexNijjar commented on build.gradle.kts
> +        "modCompileOnly"(group = "me.shedaniel", name = "REIPluginCompatibilities-forge-annotations", version = "8.+")
should be `compileOnly` and should be moved to `common/build.gradle.kts`
so:
`compileOnly(group = "me.shedaniel", name = "REIPluginCompatibilities-forge-annotations", version = "8.+")`

2024-03-24 01:24 UTC, AlexNijjar commented on common/src/main/java/earth/terrarium/adastra/common/compat/rei/displays/CompressingDisplay.java
> +@REIPluginCompatIgnore
This seems to be missing an import?

`import me.shedaniel.rei.plugincompatibilities.api.REIPluginCompatIgnore;`

2024-03-26 01:12 UTC, KiriKaz commented
Look good now? @AlexNijjar

2024-03-26 01:20 UTC, AlexNijjar approved these changes
LGTM, thank you.

2024-03-26 01:21 UTC, merged