Adding #c:wrenches and #forge:wrench tags
terrarium-earth/Ad-Astra pull request #553
Opened 2024-05-06 22:35 UTC by KalWantsPizza

QOL enhancement for users with Create Mod: allows Ad Astra wrench to be used in place of Create wrench. (Issue https://github.com/terrarium-earth/Ad-Astra/issues/552)

2024-05-06 22:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/terrarium-earth/Ad-Astra?pullRequest=553) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/terrarium-earth/Ad-Astra?pullRequest=553) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/terrarium-earth/Ad-Astra?pullRequest=553) it.</sub>

2024-05-31 00:42 UTC, AlexNijjar requested changes
These cannot be in the generated folder. this folder is specificly for assets that are generated in code and get replaced every time datagen is run. Please move to `common/src/main/resources/data`

2024-05-31 00:43 UTC, AlexNijjar commented
also, `"replace": false,` is unnecessary as it's false by default.

2024-06-01 20:54 UTC, KalWantsPizza commented
Thanks for the clarification! I'm still new to mods, I think it should be good now.

2024-06-01 20:59 UTC, AlexNijjar approved these changes

2024-06-01 20:59 UTC, merged